version: "3"

services:
  appbackend:
    container_name: app-backend
    build:
      args:
        user: sammy
        uid: 1000
      context: ./backend
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysqlapp
    ports:
      - 6024:6001
    env_file:
      - ./backend/.env
    networks:
      - app-network

  appfrontend:
    container_name: app-frontend
    build:
      context: ./frontend 
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    depends_on:
      - appbackend
    networks:
      - app-network

  nginxapp:
    container_name: nginx-backend
    image: nginx:1.15.6-alpine
    # image: 1.21.1-alpine
    ports:
      - 885:80
    volumes:
      - ./:/app
      - ./backend/docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - appbackend
    networks:
      - app-network

  mysqlapp:
    image: mysql:5.7.22
    command: --max_allowed_packet=325058560
    container_name: mysql-backend
    restart: unless-stopped
    tty: true
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdataapp:/var/lib/mysql/
    networks:
      - app-network

  redis:
    image: redis:6.2.4
    container_name: redis-backend
    ports:
      - "6384:6379"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdataapp:
    driver: local
