openapi: 3.0.3
info:
  title: 'Sfeduteacher API'
  description: 'The list of Sfeduteacher API''s.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths: []
tags: []
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
